mariadb:
  enabled: false
  fallback: file

  host: 127.0.0.1
  port: 3306
  database: backupmaster
  username: root
  password: ''

  table: backupmaster


default: file


file:
  enabled: true
  directory: ""
  zip_dir: ""

mongodb:
  enabled: false
  fallback: mysql

  ip: 127.0.0.1
  port: 27017
  auth-source: admin
  username: root
  password: ''

  database: backupmaster
  collection: worlds